Repository ikryukov/Strelka, pull requests merged in 2021-03, with the labels that each got.

#33 Ms 24i
  CMakeLists.txt
  include/modelloader/modelloader.h
  include/render/render.h
  include/render/renderpass.h
  include/render/vertex.h
  include/scene/scene.h
  misc/old/cube.mtl
  misc/old/cube.obj
  misc/old/textures/awesomeface.png
  misc/old/textures/brickwall.png
  misc/old/textures/container.jpg
  misc/old/viking_room.obj
  misc/old/viking_room.png
  misc/old/white.jpg
  misc/red-brick-wall.jpg
  shaders/simple.hlsl
  src/modelloader/modelloader.cpp
  src/render/render.cpp
  src/render/renderpass.cpp
  src/scene/scene.cpp
  src/ui/ui.cpp
Labels: enhancement

#35 fix MTL
  src/modelloader/modelloader.cpp
Labels: enhancement

#36 Small fixes
  .clang-format
  include/render/render.h
  shaders/simple.hlsl
  src/render/renderpass.cpp
Labels: bug, enhancement

#39 Compute shader support
  CMakeLists.txt
  include/render/computepass.h
  include/render/render.h
  include/shadermanager/ShaderManager.h
  shaders/compute.hlsl
  src/render/computepass.cpp
  src/render/render.cpp
  src/shadermanager/ShaderManager.cpp
Labels: enhancement

#42 Texture manager
  CMakeLists.txt
  include/modelloader/modelloader.h
  include/render/computepass.h
  include/render/render.h
  include/render/renderpass.h
  include/resourcemanager/resourcemanager.h
  include/scene/scene.h
  include/shadermanager/ShaderManager.h
  include/texturemanager/texturemanager.h
  misc/cube.mtl
  shaders/simple.hlsl
  src/modelloader/modelloader.cpp
  src/render/computepass.cpp
  src/render/render.cpp
  src/render/renderpass.cpp
  src/resourcemanager/resourcemanager.cpp
  src/scene/scene.cpp
  src/texturemanager/texturemanager.cpp
Labels: enhancement

#41 Direct light
  include/render/render.h
  include/render/renderpass.h
  include/scene/scene.h
  include/ui/ui.h
  shaders/simple.hlsl
  src/render/render.cpp
  src/render/renderpass.cpp
  src/ui/ui.cpp
Labels: enhancement

#40 Phong model
  CMakeLists.txt
  include/render/computepass.h
  include/render/render.h
  include/render/renderpass.h
  include/scene/camera.h
  include/scene/glm-wrapper.hpp
  include/scene/scene.h
  misc/CornellBox-Sphere.mtl
  misc/CornellBox-Sphere.obj
  shaders/simple.hlsl
  src/modelloader/modelloader.cpp
  src/render/computepass.cpp
  src/render/render.cpp
  src/render/renderpass.cpp
  src/scene/camera.cpp
  src/scene/scene.cpp
  src/texturemanager/texturemanager.cpp
  tests/scene/tests_scene.cpp
  tests/shadermanager/tests_shadermanager.cpp
Labels: enhancement

#49 Fix glm
  include/scene/glm-wrapper.hpp
  include/scene/scene.h
  src/scene/camera.cpp
Labels: bug
